M48
; DRILL file {KiCad 8.0.4} date 2024-12-05T15:50:01-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-05T15:50:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C4.300
%
G90
G05
T1
X116.0Y-57.0
X116.0Y-114.0
X163.0Y-58.5
X163.0Y-128.0
M30
